### ISSUE TITLE
Gestion de stockage de fichier au niveau base de donnée

### ISSUE THREAD

**Issue by thibaudsalsa** [carbontracking/upscribers#10]
- Comment stocker les fichiers
- Comment relier les fichier aux utilisateurs 
- Chaque fichier doit posseder les informations qui permettent de le tracer 
  - uploaded by
  - date of upload
  - type
  - publique / privé
  - (tags) Comment mieu gerer les metadonnées de facon flexible ?
    - tag geré par utilisateur non createur du fichier

**Comment by thibaudsalsa** [comment]
- A l'aide des outils de node et d'express sur le serveur

**Comment by carbontracking** [comment]
- [x] Comprendre comment télécharger un fichier sur le serveur et le stocker. 
  - A noter que tous les fichiers vont être stockés dans un seul répertoire.
  - 2017/09/20 : Fait en utilisant [bookshelf.js](https://www.npmjs.com/package/bookshelf) et knex qui sont livrés avec le boilerplate utilisé.
    - [Un article qui parle de CRUD](https://www.sitepoint.com/getting-started-bookshelf-js/) en utilisant bookshelf.js, au moin la partie CR
  - Est-ce que c'est le bon choix ?? Le concurrent sequelize.js a 7 fois plus de téléchargements dans la dernière semaine.
  - Et est-ce qu'un ORM est vraiment obligatoire ??
    - Pourquoi pas utiliser un module mysql pur [comme ici](https://www.sitepoint.com/using-node-mysql-javascript-client/)  ?? Ca nous fait travailler avec des queries SQL purs.
- [x] Comprendre comment mettre à jour le tableau data_file une fois un fichier téléchargé sur le serveur
  - Il faut non seuement stocker le lien vers le fichier mais aussi au moins un exemple de champ texte pour prouver que n'importe lequel méta-donnée peut être stické.
- [x] Quand un user se connecte, vérifier que nous pouvons créer un query côté serveur qui récupère tous le fichiers téléchargés que par cet utilisateur.
  - A tester avec multiple users connectés en même temps.
  - A tester en ligne de commande sur serveur ou en query SQL d'abord
- [x] A l'affichage du homepage pour un user connecté, créer le code handlebars nécessaire à generer un tableau montrant tous les fichiers téléchargés par le user

**Comment by Rchatain** [comment]
- Champs mis à jour : La gestion de stockage est opérationnelle.
- Concernant Sequelize : 
  - Il est le concurrent le plus populaire par rapport à objection, ou encore sql-bricks, cependant, malgré la différence frappante de nombre de téléchargement, Bookshelf est loin d'être inconnu dans le monde de nodejs (actuellement le 2è le plus téléchargé).  Sa documentation est claire en plus d'avoir une grosse communauté derrière elle.
  - Sequelize est un argument de choix (notamment le fait qu'il supporte bien plus de base de données que Bookshelf), mais demande bien plus de dépendances à d'autres modules pour les mêmes fonctionnalités que propose Bookshelf.
  - Bookshelf est une solution légère et adaptée qui a été développé autour de Knex, un constructeur SQL que le projet utilise.
- Concernant l'utilité d'un ORM : 
  - Un article intéressant qui explique en pratique l'utilité d'un ORM : https://www.developpez.com/actu/61252/-ORM-or-not-ORM-faut-il-les-utiliser-ou-continuer-d-ecrire-simplement-des-requetes-SQL/ (L'article prend des framework php comme exemple, le principe reste le même)
  - Très facile à prendre en main, il n'est pas forcément obligatoire de l'utiliser. Les requêtes SQL sont toujours disponible, mais la possibilité de traiter les données via ORM (avec les Collections, Modeles, etc...) donne un certain confort à la programmation.

**Comment by Rchatain** [comment]
Données stockées pour un fichier :
- ID
- Nom du fichier
- Titre du fichier (choisi par l'utilisateur lors de l'upload)
- Lien du fichier
- ID de l'utilisateur qui upload le fichier
- Description du fichier (défini par l'utilisateur)
- Date de création (upload) et Date d'édition
- Booléen pour accès public / privé
  - La colonne "tag" n'est pas encore implémentée.

Concernant le stockage de fichier :
- Le fichier est _pour le moment_ stocké sur le serveur en interne
- L'implémentation d'un cloud est prévu (Amazon Web Services, ...)

**Comment by Rchatain** [comment]
Mise à jour des colonnes de base de donées : 
 - Nouvelle colonne "key name" : utilisé pour intéragir avec le service AWS S3
 - Colonne "Lien du fichier" supprimé, du fait de la colonne "key name", ainsi que les URLs sont désormais privés
 - Nouvelle colonne "type" : le type du fichier

Les fichiers sont stockés sur un service externe (AWS S3). La gestion actuelle de stockage de fichiers est disponible désormais sur la page principale de l'application.
