### ISSUE TITLE
MongoDB vs mySQL

### ISSUE THREAD

**Issue by thibaudsalsa** [carbontracking/upscribers#16]
http://insertafter.com/fr/blog/retour_xp_mongodb.html

**Comment by Rchatain** [comment]
https://www.quora.com/Which-would-be-the-best-database-for-storing-images-and-videos-in-large-numbers

**Comment by thibaudsalsa** [comment]
MongoDB est très bien pour stocker des donnés qui ne sont pas stable, qui ont l'habitude de changer de valeur (exemple: prix d'un objet).
Cependant pour rajouter des informations comme ajouter de nouveau point de vente la structre de MySQL est plus simple.

Cependant après avoir travaillé sur le projet nous pensons que stocker les images/fichiers/html/.... sur la base de donnée est un mauvaise idée, autant les stocker sur le serveur.

**Comment by carbontracking** [comment]
MySQL donc.
