### ISSUE TITLE
Things to do for Sept 29

### ISSUE THREAD

**Issue by carbontracking** [carbontracking/upscribers#18]
- [x] Bouger le champ Recherche utilisateurs en bas de la page
- [x] Implémenter "Suppression"
  - Utiliser xmlhttprequest pour mise à jour sans recharger la page
- [x] Implémenter "Modification"
  - Utiliser xmlhttprequest pour mise à jour sans recharger la page
- [x] Créer meta-donnée type radio button (Privée/Publique) pour un nouveau fichier et aussi la partie modification
- [x] Colonne : Access , soit Public, soit privée
- [x] Icones horizontales
- [x] Implémenter le lancement d'UpBrowser en cliquant qq part
- [x] Corriger Focus problème qui fait que la page saute avec un écran étroit
- [x] Corriger le auto scroll quand on se déplace
- [x] Corriger la lecture de li, chaque li doit être traité comme une phrase
- [x] relier les deux sélections (structure/phrase) pour continer la lecture par phrase après chaque déplacement par élément structurel
- [x] Vérifier le cas ou il y a multiples phrases dans un li
- [x] Vérifier que le déplacement phrase par phrase est suivi par l'affichage

**Comment by Rchatain** [comment]
- Le champs "Recherche utilisateur" est déplacé.
 - Le bouton d'action "Afficher" fait fonctionner UpBrowser.
   - Le script est censé fonctionner pour un fichier HTML seulement. Comment faire réagir le bouton pour les autres types de fichier ?
 - Le bouton d'action "Supprimer" supprime correctement le fichier concerné.

**Comment by thibaudsalsa** [comment]
- le focus ce fait maintenant uniquement au debut et a la fin de la page
 - les problemes liés au tts sont corrigés, la voix fonction sur linux et windows sur chrome opera firefox safari

**Comment by thibaudsalsa** [comment]
la lecture phrase par phrase ne prononce que le alt d'une image et non ca source comme avant

de plus la lecture phrase par phrase annonce le debut d'un lien ainsi que la fin, sans lire l'url la phrase qui possède donc un hyperlien de ne sera donc plus coupée.

**Comment by Rchatain** [comment]
- La modification est implémentée : la mise à jour est dynamique et ne recharge pas la page
  - La suppression du fichier est implémentée sans XMLHttpRequest pour le moment
- L'utilisateur peut désormais choisir de mettre son fichier en public ou en privé dès l'upload de l'image avec un checkbox. Il peut modifier son choix avec le bouton "modification"
  - La colonne "public_access" a migré sur le serveur. Tous les fichiers sont de base "privé".
- Le tableau affiche les boutons d'actions à l'horizontale

**Comment by Rchatain** [comment]
- La suppression du fichier se fait sans recharge de page.

Toutes les tâches sont accomplies, je ferme l'issue.
