### ISSUE TITLE
Choose backend for UpStore

### ISSUE THREAD

**Issue by carbontracking** [carbontracking/upscribers#2]
- node.js + express.js + mysql/mongodb
  - See [this boilerplate](https://github.com/sahat/hackathon-starter) (node/express/mongodb) 
- meteor.js
  - Do we need DDP ?
- Interesting boilerplate generator http://megaboilerplate.com/

**Comment by thibaudsalsa** [comment]
- Etudier avantages inconvéviants météor et express (voir autre...)
- Etre conscien des fonctionnalité de interressante mais potentiellement inutils de météor (DDP, dev mobile..)
- Etudier mongoDB et MySQL (surtout dans la gestion de gros fichier)

**Comment by thibaudsalsa** [comment]
installer un ou plusieurs boilerplates

**Comment by Rchatain** [comment]
Le projet se base sur du NodeJS, ExpressJS, MySQL, et Handlebars.
