### ISSUE TITLE
Implement authentication in Upstore

### ISSUE THREAD

**Issue by carbontracking** [carbontracking/upscribers#3]
- OAuth (Twitter/Facebook/Google/LinkedIn etc.)
- Local authentication (perhaps using passport.js for node/express)
- must implement forgotten password etc.
- [This boilerplate](https://github.com/sahat/hackathon-starter) (node/express) already includes all that

**Comment by Rchatain** [comment]
Implemented : 
- OAuth (Twitter, Facebook, Google)
- Local Authentication

**Comment by carbontracking** [comment]
Completed
