### ISSUE TITLE
Trouver la solution multi-crop pour OCR

### ISSUE THREAD

**Issue by carbontracking** [carbontracking/upscribers#39]
- http://www.isdntek.com/tagbot/imap.htm
  - Montre comment créer des multiples zones dans un image
  - Renvoi les coordonnées
- jcrop

**Comment by thibaudsalsa** [comment]
http://jcrop.org/demos/panel
peu faire du multi crop

**Comment by carbontracking** [comment]
Jcrop pour l'interface
Croppie pour le code qui extrait le zone croppé et crée un base64 ou blob
A chaque crop, envoyer les co-ordonnées au code extrait de croppie
